### ISSUE TITLE
Polikilinik Randevular Tabs Yapısı

### ISSUE THREAD

**Issue by FatihG34** [Stock-Management-System/dentalApp#19]
Tab yapısı components halinde kurulacak
![Image](https://user-images.githubusercontent.com/98221928/202776514-bcfbe741-dbbc-49c0-ae93-8ea873a2da20.png)

**Comment by omersb** [comment]
![Image](https://user-images.githubusercontent.com/98221928/202805907-51f0e0ad-a85b-4f3f-9758-3edb36e6722f.png)
